### ISSUE TITLE
flutter gen 1x 2x 3x support is not friendly

### ISSUE THREAD

**Issue by OHeroJ** [FlutterGen/flutter_gen#219]
For example, I don't need 1x image, how to deal with it？

```
assets/
    images/
          2.0x/a.png
          3.0x/a.png
```

```yaml
assets:
   - assets/images/
```

i think, `flutter_gen` should generate:

```yaml
assets:
   - assets/images/
   - assets/images/a.png   # generated
   - ....
```

```dart
class $AssetsImagesGen {
  const $AssetsImagesGen();

  /// File path: assets/images/a.png
  AssetGenImage get a =>
      const AssetGenImage('assets/images/a.png'); 
}
```

**Comment by ZhZhZhen** [comment]
in this way, won't this file get very large?

**Comment by OHeroJ** [comment]
> in this way, won't this file get very large?

just use 3x ?

**Comment by suli1** [comment]
any update?

**Comment by bramp** [comment]
I'm confused what the problem is.

Flutter's [Resolution aware images](https://docs.flutter.dev/ui/assets/assets-and-images#resolution-aware) is what determines how the assets are imported/used. FlutterGen is just following its convention.

However, https://stackoverflow.com/a/60522464/88646 shows a workaround for flutter, where you can specify the 1.0x image, without it actually being included. Perhaps that will do what you need?

**Comment by MrLittleWhite** [comment]
same issue

**Comment by AlexV525** [comment]
The gen plugin provides no extra handling than what Flutter has already done. Resolution-aware resources are designed to be organized as primary resource + variants folders. Assets in variant folders without a primary resource will not recognized as a varianted resource. For variant assets, do not include them in the pubspec, which will help to produce valid generated code, or try excluding your variant pattern in the build configuration.
