### ISSUE TITLE
Question: Why use getter method?

### ISSUE THREAD

**Issue by nekocode** [FlutterGen/flutter_gen#23]
Is there any reason causes this library has to use the getter method to get value? It makes it impossible to assign a value in some cases. For example, assigning a default value:

![image](https://user-images.githubusercontent.com/4783781/92443341-f516be00-f1e3-11ea-9b42-ffb61a800451.png)

**Comment by lcdsmao** [comment]
Hi @nekocode!
Thanks for your feedback.

It seems like this problem does not relate to the getter method, but related to the path like structure we want to achieve.

For example, after changing the getter into a field it still cannot be used as the default parameter:
```dart
class Foo {
  static const bar = Bar();
}

class Bar {
  const Bar();

  final value1 = "";
  String get value2 => "";
}

void test({
  String value1 = Foo.bar.value1, // The default value of an optional parameter must be constant.
  String value2 = Foo.bar.value2, // The default value of an optional parameter must be constant.
}) {
  //
}
```

Since Dart does not support the nested class, the `Assets` class needs to hold some instances which hold the real asset path. And this caused the inconvenience usage for the default value. 😢

Speaking back to the getter, we just followed this lint rule [avoid_field_initializers_in_const_classes](https://dart-lang.github.io/linter/lints/avoid_field_initializers_in_const_classes.html).

Any further suggestions welcome! 😀

**Comment by nekocode** [comment]
Actually I means why not use static const field:

```dart
class Foo {
  static const bar = Bar();
}

class Bar {
  const Bar();

  static const value1 = "";
}
```

So that we can access the const value1 by `Foo.bar.value1`.

**Comment by nekocode** [comment]
Since all generated values look like needn't to be evaluated in runtime? (can be static).

**Comment by nekocode** [comment]
But I know that is not a good design because the `bar` instance here has no hold any properties. It just like an access helper.

JFYI. Close it now. Thanks for reply.
