### ISSUE TITLE
Is ImageProvider no longer supported?

### ISSUE THREAD

**Issue by IvanYue** [FlutterGen/flutter_gen#235]
flutter_gen_runner: ^4.1.6
![image](https://user-images.githubusercontent.com/14163140/170691669-a46db8bb-513f-4257-b062-1e9bf1854837.png)

**Comment by lcdsmao** [comment]
@IvanYue 
>Is ImageProvider no longer supported

Yes.

Can you try `Assets.images.icon.allInOne.image(width: ...)` or `Image.asset(Assets.images.icons.allInOne.path, width: ...)`?

**Comment by kolotum** [comment]
I like the new way introduced in 4.2:

```dart
Assets.images.icon.allInOne.image(
  width: Get.width,
  height: 267.h,
  fit: BoxFit.fill,
)
```

But I am not sure if `path` works when `package_parameter_enabled: true` is set.

Also right now we require the inheritance of AssetImage, because we can use ImageProvider in several places, e.g. to preload images.

I think we can still use the new `image()` method and re-add `AssetImage` inheritance like:

```dart
class AssetGenImage extends AssetImage {
  const AssetGenImage(String assetName) : super(assetName, package: 'my_flutter_package');
```

**Comment by lcdsmao** [comment]
>But I am not sure if path works when package_parameter_enabled: true is set.

It works. Please see here:
https://github.com/FlutterGen/flutter_gen/blob/05e307b298316c2b93634902e520b435ed2e1db5/example/lib/main.dart#L43

We change to `Image.asset` constructor because it supports more optional parameters.

>Also right now we require the inheritance of AssetImage, because we can use ImageProvider in several places, e.g. to preload images.

You can still get provider via `Assets.images.allInOne.image(...).image`.
This `ImageProvider` should be a more correct one, which respect the optional parameters, than the previous inheritance one.

**Comment by kolotum** [comment]
> > But I am not sure if path works when package_parameter_enabled: true is set.
> 
> It works. Please see here:
> 
> https://github.com/FlutterGen/flutter_gen/blob/05e307b298316c2b93634902e520b435ed2e1db5/example/lib/main.dart#L43

Just to clarify: My expectation was that we can use `path` to fully address the image source. Using the code from example:

```dart
Assets.images.chip1.image(), // works
Image.asset(Assets.images.chip1.path), // works
// Use from example_resource package.
res.Assets.images.flutter3.image(), // works
Image.asset(res.Assets.images.flutter3.path), // unable to load, requires packages parameter
Image.asset(res.Assets.images.flutter3.path, package: 'example_resources'),
```

`res.Assets.images.flutter3.path` only works with `Image.asset` when we set the `package` parameter.

**Comment by kolotum** [comment]
> You can still get provider via `Assets.images.allInOne.image(...).image`.
> This `ImageProvider` should be a more correct one, which respect the optional parameters, than the previous inheritance one.

Thank you for pointing this option out. Do we have any performance impacts when we create an `Image` widget for each asset we want to preload/precache?

**Comment by erleizh** [comment]
need `ImageProvider provider() => AssetImage(_assetName);`

**Comment by dokkaebi** [comment]
What is the best way to create a `DecorationImage` now?

**Comment by anandsubbu007** [comment]
any update?
