### ISSUE TITLE
[Feature Request] Add support for adding assets from a package

### ISSUE THREAD

**Issue by jorgecoca** [FlutterGen/flutter_gen#50]
Hello! 👋 

As a developer, I work on packages that need to contain assets. When that happens, those assets need to be referenced in a different way (see links below):

* https://stackoverflow.com/questions/54740732/how-to-add-assets-in-flutter-package-plugin-development
* https://flutter.dev/docs/development/ui/assets-and-images#bundling-of-package-assets

It'd be amazing for `flutter_gen` to support this use case.

If you believe this is a valid use case, I'd be more than happy to take a look and come up with a proposal / pull request.

Thank you! 💯

**Comment by wasabeef** [comment]
I'm also thinking about the best way.
If anyone has a good idea, it would be helpful if you could get a pull request.

**Comment by korzonkiee** [comment]
Hey!

I think a have an idea for a potential solution that might solve that problem.

We could:

1. Extend `FlutterGen` with an additional `package` parameter, so that the user can define it as follows:
  ```
  flutter_gen:
  output: lib/generated/
  package: my_ui_package
  lineLength: 80
  integrations:
    flutter_svg: true
  ```
2. Modify [_assetGenImageClassDefinition](https://github.com/FlutterGen/flutter_gen/blob/main/lib/src/generators/assets_generator.dart#L307) so that it takes `package` parameter. It would require transforming this constant string value into a parameterized function.
3. Pass the `package` parameter to the `AssetImage.super(assetName, package)` [super constructor](https://github.com/FlutterGen/flutter_gen/blob/main/lib/src/generators/assets_generator.dart#L312).

Additionally, SVG integration would need to be updated as follows:
1. Convert [`Integration.classOutput` getter](https://github.com/FlutterGen/flutter_gen/blob/main/lib/src/generators/integrations/integration.dart#L8) to method with `package` argument.
2. Pass `package` as a [default value for `SvgPicture.package` field](https://github.com/FlutterGen/flutter_gen/blob/main/lib/src/generators/integrations/svg_integration.dart#L21).

Let me know what you think about that solution @wasabeef @jorgecoca

**Comment by orestesgaolin** [comment]
I saw that this landed in 3.1.1 but somehow my assets aren't generated with `package` parameter:


```dart
// @dart = 2.10
/// GENERATED CODE - DO NOT MODIFY BY HAND
/// *****************************************************
///  FlutterGen
/// *****************************************************

import 'package:flutter/widgets.dart';

class Assets {
  Assets._();

  static const AssetGenImage duck = AssetGenImage('assets/duck.png');
}

class AssetGenImage extends AssetImage {
  const AssetGenImage(String assetName)
      : _assetName = assetName,
        super(assetName);
  final String _assetName;

  Image image({
    Key key,
    ImageFrameBuilder frameBuilder,
    ImageLoadingBuilder loadingBuilder,
    ImageErrorWidgetBuilder errorBuilder,
    String semanticLabel,
    bool excludeFromSemantics = false,
    double width,
    double height,
    Color color,
    BlendMode colorBlendMode,
    BoxFit fit,
    AlignmentGeometry alignment = Alignment.center,
    ImageRepeat repeat = ImageRepeat.noRepeat,
    Rect centerSlice,
    bool matchTextDirection = false,
    bool gaplessPlayback = false,
    bool isAntiAlias = false,
    FilterQuality filterQuality = FilterQuality.low,
  }) {
    return Image(
      key: key,
      image: this,
      frameBuilder: frameBuilder,
      loadingBuilder: loadingBuilder,
      errorBuilder: errorBuilder,
      semanticLabel: semanticLabel,
      excludeFromSemantics: excludeFromSemantics,
      width: width,
      height: height,
      color: color,
      colorBlendMode: colorBlendMode,
      fit: fit,
      alignment: alignment,
      repeat: repeat,
      centerSlice: centerSlice,
      matchTextDirection: matchTextDirection,
      gaplessPlayback: gaplessPlayback,
      isAntiAlias: isAntiAlias,
      filterQuality: filterQuality,
    );
  }

  String get path => _assetName;
}
```


pubspec.yaml:

```yaml
flutter_gen:
  output: lib/src/generated/
  line_lenght: 80
  assets:
    package_parameter_enabled: true
  integrations:
    flutter_svg: true
```

**Comment by wasabeef** [comment]
Thanks

**Comment by om-ha** [comment]
Hey @jorgecoca

As an app developer following this issue's approach, we want to consume the package's assets. Do we have to set every single image asset as an entry in the consumer app's `pubspec.yaml` file? I hope there's a way to overcome this otherwise it would be too verbose.

See [this article](https://medium.com/flutter-community/including-assets-in-a-flutter-package-dd4a82a38ca9#5b3e) -> `Example 1: shrine_images` -> `How an app developer uses the package`.
